<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ST558 Project 3 – Derek Chao - Modeling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">ST558 Project 3 – Derek Chao</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./eda.html">
 <span class="menu-text">EDA</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Modeling.html" aria-current="page">
 <span class="menu-text">Modeling</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#data-and-split" id="toc-data-and-split" class="nav-link active" data-scroll-target="#data-and-split">Data and split</a>
  <ul class="collapse">
  <li><a href="#splitting-the-data" id="toc-splitting-the-data" class="nav-link" data-scroll-target="#splitting-the-data">Splitting the data</a></li>
  <li><a href="#predictors" id="toc-predictors" class="nav-link" data-scroll-target="#predictors">Predictors</a></li>
  <li><a href="#pre-processing" id="toc-pre-processing" class="nav-link" data-scroll-target="#pre-processing">Pre-processing</a></li>
  <li><a href="#pick-the-best-tree-by-mean-log-loss" id="toc-pick-the-best-tree-by-mean-log-loss" class="nav-link" data-scroll-target="#pick-the-best-tree-by-mean-log-loss">Pick the best tree by mean log loss</a></li>
  <li><a href="#evaluate-on-test-set" id="toc-evaluate-on-test-set" class="nav-link" data-scroll-target="#evaluate-on-test-set">Evaluate on test set</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#random-forest-definition" id="toc-random-forest-definition" class="nav-link" data-scroll-target="#random-forest-definition">Random Forest Definition</a></li>
  <li><a href="#evaluate-on-test-set-1" id="toc-evaluate-on-test-set-1" class="nav-link" data-scroll-target="#evaluate-on-test-set-1">Evaluate on test set</a></li>
  </ul></li>
  <li><a href="#final-model-selection" id="toc-final-model-selection" class="nav-link" data-scroll-target="#final-model-selection">Final Model Selection</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Modeling</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tidymodels_prefer</span>()</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rsample) </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(doParallel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Our goal is to <strong>predict <code>diabetes_binary</code></strong>, and to do so we will compare two models: a <strong>classification tree</strong> and a <strong>random forest</strong>. Each model will be evaluated using <strong>log-loss</strong> as the primary performance metric, with <strong>5-fold cross-validation</strong> applied on the <strong>70/30 train/test split</strong> to assess how well each approach generalizes to unseen data.</p>
<section id="data-and-split" class="level2">
<h2 class="anchored" data-anchor-id="data-and-split">Data and split</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/diabetes_binary_health_indicators_BRFSS2015.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>() <span class="sc">|&gt;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">diabetes_binary =</span> <span class="fu">factor</span>(diabetes_binary, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No_Diabetes"</span>, <span class="st">"Diabetes"</span>)),</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">high_bp  =</span> <span class="fu">factor</span>(high_bp,  <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)),</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">high_chol =</span> <span class="fu">factor</span>(high_chol, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)),</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">chol_check =</span> <span class="fu">factor</span>(chol_check, <span class="at">level =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)),</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">smoker =</span> <span class="fu">factor</span>(smoker, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)),</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">stroke =</span> <span class="fu">factor</span>(stroke, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)),</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">heart_diseaseor_attack =</span> <span class="fu">factor</span>(heart_diseaseor_attack, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>,     <span class="st">"Yes"</span>)),</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">phys_activity =</span> <span class="fu">factor</span>(phys_activity, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)),</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">fruits =</span> <span class="fu">factor</span>(fruits, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)),</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">veggies =</span> <span class="fu">factor</span>(veggies, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)),</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">hvy_alcohol_consump =</span> <span class="fu">factor</span>(hvy_alcohol_consump, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>  )),</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">any_healthcare =</span> <span class="fu">factor</span>(any_healthcare, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)),</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">no_docbc_cost =</span> <span class="fu">factor</span>(no_docbc_cost, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)),</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    gen_hlth <span class="ot">&lt;-</span> <span class="fu">factor</span>(</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>      gen_hlth,</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Excellent"</span>, <span class="st">"Very Good"</span>, <span class="st">"Good"</span>, <span class="st">"Fair"</span>, <span class="st">"Poor"</span>)</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">diff_walk =</span> <span class="fu">factor</span>(diff_walk, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)),</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex =</span> <span class="fu">factor</span>(sex, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Female"</span>, <span class="st">"Male"</span>)),</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    education <span class="ot">&lt;-</span> <span class="fu">factor</span>(</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>      education,</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>,</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>        <span class="st">"K-8"</span>,</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Grades 1-8"</span>,</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Grades 9-11"</span>,</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>        <span class="st">"High School / GED"</span>,</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Some College"</span>,</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>        <span class="st">"College Graduate"</span></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>    income <span class="ot">&lt;-</span> <span class="fu">factor</span>(</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>      income,</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>,</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>        <span class="st">"&lt;10k"</span>,</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>        <span class="st">"10-15k"</span>,</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>        <span class="st">"15-20k"</span>,</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>        <span class="st">"20-25k"</span>,</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>        <span class="st">"25-35k"</span>,</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>        <span class="st">"35-50k"</span>,</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>        <span class="st">"50-75k"</span>,</span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>        <span class="st">"75k+"</span></span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>    <span class="at">age =</span> <span class="fu">factor</span>(</span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>      age,</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">13</span>,</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(</span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>        <span class="st">"18–24"</span>, <span class="st">"25–29"</span>, <span class="st">"30–34"</span>, <span class="st">"35–39"</span>,</span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>        <span class="st">"40–44"</span>, <span class="st">"45–49"</span>, <span class="st">"50–54"</span>, <span class="st">"55–59"</span>,</span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a>        <span class="st">"60–64"</span>, <span class="st">"65–69"</span>, <span class="st">"70–74"</span>, <span class="st">"75–79"</span>,</span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a>        <span class="st">"80+"</span></span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="splitting-the-data" class="level3">
<h3 class="anchored" data-anchor-id="splitting-the-data">Splitting the data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>data_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(data, <span class="at">prop =</span> <span class="fl">0.7</span>, <span class="at">strata =</span> diabetes_binary)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> <span class="fu">training</span>(data_split)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>small_train <span class="ot">&lt;-</span> train_data <span class="sc">|&gt;</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">sample_frac</span>(<span class="fl">0.2</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>test_data  <span class="ot">&lt;-</span> <span class="fu">testing</span>(data_split)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="predictors" class="level3">
<h3 class="anchored" data-anchor-id="predictors">Predictors</h3>
<p>I am choosing to use all predictors.</p>
</section>
<section id="pre-processing" class="level3">
<h3 class="anchored" data-anchor-id="pre-processing">Pre-processing</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>diabetes_recipe <span class="ot">&lt;-</span> <span class="fu">recipe</span>(diabetes_binary <span class="sc">~</span> ., <span class="at">data =</span> train_data) <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_zv</span>(<span class="fu">all_predictors</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Set-up CV and setup Metric = ‘log-loss’</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>folds <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(small_train, <span class="at">v =</span> <span class="dv">5</span>, <span class="at">strata =</span> diabetes_binary)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>logloss_metric <span class="ot">&lt;-</span> <span class="fu">metric_set</span>(mn_log_loss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Classification Tree Definition</p>
<p>A <strong>classification tree</strong> is a predictive modeling method that uses a tree-like structure to classify observations into categories. The algorithm repeatedly splits the data into smaller and more similar groups based on predictor variables. At each split, it chooses the variable and cutoff that best separate the classes—typically using measures like Gini impurity or information gain. These splits continue until the tree reaches a stopping rule, such as a minimum number of observations in a node. The final leaves of the tree represent predicted classes. Classification trees are easy to interpret because they mimic human decision-making: you follow a sequence of “if–then” rules to arrive at a prediction. They can be unstable and prone to overfitting, which is why ensemble methods like random forests are often used to improve performance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>tree_spec <span class="ot">&lt;-</span> <span class="fu">decision_tree</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">mode =</span> <span class="st">"classification"</span>,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">cost_complexity =</span> <span class="fu">tune</span>(),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">tree_depth =</span> <span class="fu">tune</span>(),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">min_n =</span> <span class="fu">tune</span>()</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"rpart"</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>tree_grid_small <span class="ot">&lt;-</span> <span class="fu">grid_regular</span>(</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cost_complexity</span>(),</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tree_depth</span>(<span class="at">range =</span> <span class="fu">c</span>(3L, 9L)),</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">min_n</span>(<span class="at">range =</span> <span class="fu">c</span>(10L, 40L)),</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> <span class="dv">3</span>   </span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>tree_workflow_small <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(tree_spec) <span class="sc">|&gt;</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(diabetes_recipe)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a><span class="co"># set up parallel backend</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>cl <span class="ot">&lt;-</span> <span class="fu">makeCluster</span>(parallel<span class="sc">::</span><span class="fu">detectCores</span>() <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a><span class="fu">registerDoParallel</span>(cl)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a><span class="co"># tuning control (this is what goes in `control =`)</span></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>ctrl <span class="ot">&lt;-</span> <span class="fu">control_grid</span>(<span class="at">verbose =</span> <span class="cn">TRUE</span>, <span class="at">allow_par =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>tree_tuned_small <span class="ot">&lt;-</span> <span class="fu">tune_grid</span>(</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>  tree_workflow_small,</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> folds,</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid      =</span> tree_grid_small,</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics   =</span> logloss_metric,</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">control   =</span> ctrl</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 1/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 1/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 2/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 2/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 3/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 3/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 4/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 4/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 5/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 5/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 6/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 6/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 7/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 7/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 8/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 8/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 9/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 9/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 10/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 10/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 11/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 11/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 12/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 12/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 13/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 13/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 14/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 14/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 15/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 15/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 16/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 16/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 17/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 17/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 18/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 18/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 19/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 19/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 20/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 20/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 21/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 21/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 22/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 22/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 23/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 23/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 24/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 24/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 25/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 25/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 26/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 26/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 27/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 27/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 1/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 1/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 2/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 2/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 3/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 3/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 4/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 4/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 5/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 5/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 6/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 6/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 7/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 7/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 8/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 8/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 9/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 9/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 10/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 10/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 11/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 11/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 12/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 12/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 13/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 13/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 14/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 14/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 15/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 15/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 16/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 16/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 17/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 17/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 18/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 18/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 19/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 19/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 20/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 20/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 21/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 21/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 22/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 22/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 23/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 23/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 24/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 24/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 25/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 25/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 26/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 26/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 27/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 27/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 1/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 1/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 2/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 2/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 3/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 3/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 4/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 4/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 5/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 5/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 6/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 6/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 7/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 7/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 8/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 8/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 9/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 9/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 10/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 10/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 11/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 11/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 12/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 12/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 13/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 13/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 14/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 14/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 15/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 15/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 16/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 16/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 17/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 17/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 18/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 18/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 19/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 19/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 20/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 20/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 21/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 21/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 22/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 22/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 23/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 23/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 24/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 24/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 25/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 25/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 26/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 26/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 27/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 27/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 1/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 1/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 2/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 2/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 3/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 3/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 4/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 4/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 5/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 5/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 6/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 6/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 7/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 7/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 8/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 8/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 9/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 9/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 10/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 10/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 11/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 11/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 12/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 12/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 13/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 13/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 14/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 14/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 15/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 15/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 16/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 16/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 17/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 17/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 18/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 18/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 19/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 19/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 20/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 20/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 21/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 21/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 22/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 22/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 23/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 23/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 24/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 24/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 25/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 25/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 26/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 26/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 27/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 27/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 1/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 1/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 2/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 2/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 3/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 3/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 4/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 4/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 5/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 5/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 6/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 6/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 7/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 7/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 8/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 8/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 9/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 9/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 10/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 10/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 11/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 11/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 12/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 12/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 13/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 13/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 14/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 14/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 15/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 15/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 16/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 16/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 17/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 17/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 18/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 18/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 19/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 19/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 20/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 20/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 21/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 21/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 22/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 22/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 23/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 23/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 24/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 24/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 25/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 25/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 26/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 26/27 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 27/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 27/27 (predictions)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb282"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb282-1"><a href="#cb282-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopCluster</span>(cl)</span>
<span id="cb282-2"><a href="#cb282-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb282-3"><a href="#cb282-3" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(tree_tuned_small)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 27 × 9
   cost_complexity tree_depth min_n .metric     .estimator  mean     n   std_err
             &lt;dbl&gt;      &lt;int&gt; &lt;int&gt; &lt;chr&gt;       &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;     &lt;dbl&gt;
 1    0.0000000001          3    10 mn_log_loss binary     0.406     5 0.0000483
 2    0.0000000001          3    25 mn_log_loss binary     0.406     5 0.0000483
 3    0.0000000001          3    40 mn_log_loss binary     0.406     5 0.0000483
 4    0.0000000001          6    10 mn_log_loss binary     0.353     5 0.00480  
 5    0.0000000001          6    25 mn_log_loss binary     0.350     5 0.00467  
 6    0.0000000001          6    40 mn_log_loss binary     0.351     5 0.00416  
 7    0.0000000001          9    10 mn_log_loss binary     0.387     5 0.00708  
 8    0.0000000001          9    25 mn_log_loss binary     0.343     5 0.00496  
 9    0.0000000001          9    40 mn_log_loss binary     0.339     5 0.00546  
10    0.00000316            3    10 mn_log_loss binary     0.406     5 0.0000483
# ℹ 17 more rows
# ℹ 1 more variable: .config &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section id="pick-the-best-tree-by-mean-log-loss" class="level3">
<h3 class="anchored" data-anchor-id="pick-the-best-tree-by-mean-log-loss">Pick the best tree by mean log loss</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb284"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb284-1"><a href="#cb284-1" aria-hidden="true" tabindex="-1"></a>best_tree <span class="ot">&lt;-</span> <span class="fu">select_best</span>(tree_tuned_small, <span class="at">metric =</span> <span class="st">"mn_log_loss"</span>)</span>
<span id="cb284-2"><a href="#cb284-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb284-3"><a href="#cb284-3" aria-hidden="true" tabindex="-1"></a>best_tree</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  cost_complexity tree_depth min_n .config         
            &lt;dbl&gt;      &lt;int&gt; &lt;int&gt; &lt;chr&gt;           
1    0.0000000001          9    40 pre0_mod09_post0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb286"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb286-1"><a href="#cb286-1" aria-hidden="true" tabindex="-1"></a>tree_final_wf <span class="ot">&lt;-</span> <span class="fu">finalize_workflow</span>(tree_workflow_small, best_tree)</span>
<span id="cb286-2"><a href="#cb286-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb286-3"><a href="#cb286-3" aria-hidden="true" tabindex="-1"></a>tree_final_fit <span class="ot">&lt;-</span> <span class="fu">fit</span>(tree_final_wf, <span class="at">data =</span> train_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="evaluate-on-test-set" class="level3">
<h3 class="anchored" data-anchor-id="evaluate-on-test-set">Evaluate on test set</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb287"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb287-1"><a href="#cb287-1" aria-hidden="true" tabindex="-1"></a>tree_test_preds <span class="ot">&lt;-</span> <span class="fu">predict</span>(tree_final_fit, test_data, <span class="at">type =</span> <span class="st">"prob"</span>) <span class="sc">|&gt;</span></span>
<span id="cb287-2"><a href="#cb287-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(test_data <span class="sc">|&gt;</span> <span class="fu">select</span>(diabetes_binary))</span>
<span id="cb287-3"><a href="#cb287-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb287-4"><a href="#cb287-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mn_log_loss</span>(tree_test_preds,</span>
<span id="cb287-5"><a href="#cb287-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">truth =</span> diabetes_binary,</span>
<span id="cb287-6"><a href="#cb287-6" aria-hidden="true" tabindex="-1"></a>            .pred_Diabetes,</span>
<span id="cb287-7"><a href="#cb287-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">event_level =</span> <span class="st">"second"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 mn_log_loss binary         0.327</code></pre>
</div>
<div class="sourceCode cell-code" id="cb289"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb289-1"><a href="#cb289-1" aria-hidden="true" tabindex="-1"></a>tree_class <span class="ot">&lt;-</span> <span class="fu">predict</span>(tree_final_fit, test_data, <span class="at">type =</span> <span class="st">"class"</span>) <span class="sc">|&gt;</span></span>
<span id="cb289-2"><a href="#cb289-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(test_data <span class="sc">|&gt;</span> <span class="fu">select</span>(diabetes_binary))</span>
<span id="cb289-3"><a href="#cb289-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb289-4"><a href="#cb289-4" aria-hidden="true" tabindex="-1"></a><span class="fu">conf_mat</span>(tree_class, <span class="at">truth =</span> diabetes_binary, <span class="at">estimate =</span> .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Truth
Prediction    No_Diabetes Diabetes
  No_Diabetes       64001     8861
  Diabetes           1500     1743</code></pre>
</div>
<div class="sourceCode cell-code" id="cb291"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb291-1"><a href="#cb291-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(tree_class, <span class="at">truth =</span> diabetes_binary, <span class="at">estimate =</span> .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric  .estimator .estimate
  &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
1 accuracy binary         0.864</code></pre>
</div>
</div>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>To model the probability of diabetes, I tuned a classification tree using a stratified subsample of the training data. The tuning grid explored a range of values for the tree’s cost-complexity penalty, maximum depth, and minimum node size. After identifying the hyperparameter combination that minimized cross-validated log-loss, I refit the finalized tree on the <strong>full 70% training split</strong>.</p>
<p>To evaluate generalization performance, I predicted class probabilities for the <strong>held-out 30% test set</strong> and computed log-loss using the predicted probability of the “Diabetes” class. The tuned classification tree achieved a <strong>test log-loss of 0.32699</strong>, indicating that the model produces reasonably calibrated probability estimates for diabetes risk. This performance will serve as a benchmark when comparing against the random forest.</p>
</section>
<section id="random-forest-definition" class="level3">
<h3 class="anchored" data-anchor-id="random-forest-definition">Random Forest Definition</h3>
<p>A random forest is an ensemble learning method that builds a large number of decision trees and combines their predictions to produce a more accurate and stable classifier. Each tree in the forest is trained on a bootstrap sample of the data (sampling with replacement), and at each split, the algorithm considers only a random subset of predictors rather than all available predictors. These two sources of randomness make the individual trees more diverse. When it’s time to predict, the forest aggregates the results—typically by taking a majority vote for classification problems.</p>
<p>Random forests improve on a single tree by reducing overfitting and increasing stability. Individual trees are highly variable and sensitive to small changes in the data, but by averaging many decorrelated trees, random forests lower variance and produce more accurate, reliable predictions on new data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb293"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb293-1"><a href="#cb293-1" aria-hidden="true" tabindex="-1"></a>rf_spec <span class="ot">&lt;-</span> <span class="fu">rand_forest</span>(</span>
<span id="cb293-2"><a href="#cb293-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">mode =</span> <span class="st">"classification"</span>,</span>
<span id="cb293-3"><a href="#cb293-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">mtry  =</span> <span class="fu">tune</span>(),</span>
<span id="cb293-4"><a href="#cb293-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">trees =</span> <span class="dv">500</span>,</span>
<span id="cb293-5"><a href="#cb293-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">min_n =</span> <span class="fu">tune</span>()</span>
<span id="cb293-6"><a href="#cb293-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb293-7"><a href="#cb293-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"ranger"</span>, <span class="at">importance =</span> <span class="st">"impurity"</span>)</span>
<span id="cb293-8"><a href="#cb293-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb293-9"><a href="#cb293-9" aria-hidden="true" tabindex="-1"></a>rf_workflow_small <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span></span>
<span id="cb293-10"><a href="#cb293-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(rf_spec) <span class="sc">|&gt;</span></span>
<span id="cb293-11"><a href="#cb293-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(diabetes_recipe)</span>
<span id="cb293-12"><a href="#cb293-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb293-13"><a href="#cb293-13" aria-hidden="true" tabindex="-1"></a><span class="co"># number of predictors (for mtry upper bound)</span></span>
<span id="cb293-14"><a href="#cb293-14" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">setdiff</span>(<span class="fu">names</span>(small_train), <span class="st">"diabetes_binary"</span>))</span>
<span id="cb293-15"><a href="#cb293-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb293-16"><a href="#cb293-16" aria-hidden="true" tabindex="-1"></a>rf_grid_small <span class="ot">&lt;-</span> <span class="fu">grid_regular</span>(</span>
<span id="cb293-17"><a href="#cb293-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mtry</span>(<span class="at">range =</span> <span class="fu">c</span>(2L, p)),</span>
<span id="cb293-18"><a href="#cb293-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">min_n</span>(<span class="at">range =</span> <span class="fu">c</span>(5L, 50L)),</span>
<span id="cb293-19"><a href="#cb293-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> <span class="dv">3</span>   )</span>
<span id="cb293-20"><a href="#cb293-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb293-21"><a href="#cb293-21" aria-hidden="true" tabindex="-1"></a>cl <span class="ot">&lt;-</span> <span class="fu">makeCluster</span>(parallel<span class="sc">::</span><span class="fu">detectCores</span>() <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb293-22"><a href="#cb293-22" aria-hidden="true" tabindex="-1"></a><span class="fu">registerDoParallel</span>(cl)</span>
<span id="cb293-23"><a href="#cb293-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb293-24"><a href="#cb293-24" aria-hidden="true" tabindex="-1"></a>ctrl <span class="ot">&lt;-</span> <span class="fu">control_grid</span>(<span class="at">verbose =</span> <span class="cn">TRUE</span>, <span class="at">allow_par =</span> <span class="cn">TRUE</span>)</span>
<span id="cb293-25"><a href="#cb293-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb293-26"><a href="#cb293-26" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb293-27"><a href="#cb293-27" aria-hidden="true" tabindex="-1"></a>rf_tuned_small <span class="ot">&lt;-</span> <span class="fu">tune_grid</span>(</span>
<span id="cb293-28"><a href="#cb293-28" aria-hidden="true" tabindex="-1"></a>  rf_workflow_small,</span>
<span id="cb293-29"><a href="#cb293-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> folds,</span>
<span id="cb293-30"><a href="#cb293-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid      =</span> rf_grid_small,</span>
<span id="cb293-31"><a href="#cb293-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics   =</span> logloss_metric,</span>
<span id="cb293-32"><a href="#cb293-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">control   =</span> ctrl</span>
<span id="cb293-33"><a href="#cb293-33" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 1/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 1/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 2/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 2/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 3/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 3/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 4/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 4/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 5/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 5/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 6/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 6/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 7/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 7/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 8/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 8/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 9/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold1: preprocessor 1/1, model 9/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 1/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 1/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 2/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 2/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 3/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 3/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 4/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 4/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 5/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 5/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 6/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 6/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 7/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 7/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 8/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 8/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 9/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold2: preprocessor 1/1, model 9/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 1/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 1/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 2/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 2/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 3/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 3/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 4/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 4/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 5/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 5/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 6/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 6/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 7/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 7/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 8/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 8/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 9/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold3: preprocessor 1/1, model 9/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 1/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 1/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 2/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 2/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 3/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 3/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 4/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 4/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 5/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 5/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 6/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 6/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 7/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 7/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 8/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 8/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 9/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold4: preprocessor 1/1, model 9/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 1/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 1/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 2/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 2/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 3/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 3/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 4/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 4/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 5/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 5/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 6/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 6/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 7/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 7/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 8/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 8/9 (predictions)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 9/9</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>i Fold5: preprocessor 1/1, model 9/9 (predictions)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb389"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb389-1"><a href="#cb389-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopCluster</span>(cl)</span>
<span id="cb389-2"><a href="#cb389-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb389-3"><a href="#cb389-3" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(rf_tuned_small)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 8
   mtry min_n .metric     .estimator  mean     n std_err .config        
  &lt;int&gt; &lt;int&gt; &lt;chr&gt;       &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;          
1     2     5 mn_log_loss binary     0.323     5 0.00154 pre0_mod1_post0
2     2    27 mn_log_loss binary     0.323     5 0.00157 pre0_mod2_post0
3     2    50 mn_log_loss binary     0.324     5 0.00150 pre0_mod3_post0
4    12     5 mn_log_loss binary     0.359     5 0.00664 pre0_mod4_post0
5    12    27 mn_log_loss binary     0.333     5 0.00368 pre0_mod5_post0
6    12    50 mn_log_loss binary     0.329     5 0.00370 pre0_mod6_post0
7    22     5 mn_log_loss binary     0.373     5 0.00779 pre0_mod7_post0
8    22    27 mn_log_loss binary     0.342     5 0.00577 pre0_mod8_post0
9    22    50 mn_log_loss binary     0.334     5 0.00398 pre0_mod9_post0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb391"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb391-1"><a href="#cb391-1" aria-hidden="true" tabindex="-1"></a>best_rf <span class="ot">&lt;-</span> <span class="fu">select_best</span>(rf_tuned_small, <span class="at">metric =</span> <span class="st">"mn_log_loss"</span>)</span>
<span id="cb391-2"><a href="#cb391-2" aria-hidden="true" tabindex="-1"></a>best_rf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
   mtry min_n .config        
  &lt;int&gt; &lt;int&gt; &lt;chr&gt;          
1     2    27 pre0_mod2_post0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb393"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb393-1"><a href="#cb393-1" aria-hidden="true" tabindex="-1"></a>rf_workflow <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span></span>
<span id="cb393-2"><a href="#cb393-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(rf_spec) <span class="sc">|&gt;</span></span>
<span id="cb393-3"><a href="#cb393-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(diabetes_recipe)</span>
<span id="cb393-4"><a href="#cb393-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb393-5"><a href="#cb393-5" aria-hidden="true" tabindex="-1"></a>rf_final_wf <span class="ot">&lt;-</span> rf_workflow <span class="sc">|&gt;</span> <span class="fu">finalize_workflow</span>(best_rf)</span>
<span id="cb393-6"><a href="#cb393-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb393-7"><a href="#cb393-7" aria-hidden="true" tabindex="-1"></a>rf_final_fit <span class="ot">&lt;-</span> <span class="fu">fit</span>(rf_final_wf, <span class="at">data =</span> train_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="evaluate-on-test-set-1" class="level3">
<h3 class="anchored" data-anchor-id="evaluate-on-test-set-1">Evaluate on test set</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb394"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb394-1"><a href="#cb394-1" aria-hidden="true" tabindex="-1"></a>rf_test_preds <span class="ot">&lt;-</span> <span class="fu">predict</span>(rf_final_fit, test_data, <span class="at">type =</span> <span class="st">"prob"</span>) <span class="sc">|&gt;</span></span>
<span id="cb394-2"><a href="#cb394-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(test_data <span class="sc">|&gt;</span> <span class="fu">select</span>(diabetes_binary))</span>
<span id="cb394-3"><a href="#cb394-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb394-4"><a href="#cb394-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mn_log_loss</span>(rf_test_preds,</span>
<span id="cb394-5"><a href="#cb394-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">truth =</span> diabetes_binary,</span>
<span id="cb394-6"><a href="#cb394-6" aria-hidden="true" tabindex="-1"></a>            .pred_Diabetes,</span>
<span id="cb394-7"><a href="#cb394-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">event_level =</span> <span class="st">"second"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 mn_log_loss binary         0.320</code></pre>
</div>
<div class="sourceCode cell-code" id="cb396"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb396-1"><a href="#cb396-1" aria-hidden="true" tabindex="-1"></a>rf_class <span class="ot">&lt;-</span> <span class="fu">predict</span>(rf_final_fit, test_data, <span class="at">type =</span> <span class="st">"class"</span>) <span class="sc">|&gt;</span></span>
<span id="cb396-2"><a href="#cb396-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(test_data <span class="sc">|&gt;</span> <span class="fu">select</span>(diabetes_binary))</span>
<span id="cb396-3"><a href="#cb396-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb396-4"><a href="#cb396-4" aria-hidden="true" tabindex="-1"></a><span class="fu">conf_mat</span>(rf_class, <span class="at">truth =</span> diabetes_binary, <span class="at">estimate =</span> .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Truth
Prediction    No_Diabetes Diabetes
  No_Diabetes       65175     9983
  Diabetes            326      621</code></pre>
</div>
<div class="sourceCode cell-code" id="cb398"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb398-1"><a href="#cb398-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(rf_class, <span class="at">truth =</span> diabetes_binary, <span class="at">estimate =</span> .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric  .estimator .estimate
  &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
1 accuracy binary         0.865</code></pre>
</div>
</div>
</section>
</section>
<section id="final-model-selection" class="level2">
<h2 class="anchored" data-anchor-id="final-model-selection">Final Model Selection</h2>
<p>Both the Classification Tree and Random Forest models were evaluated on the exact same test set. The difference in the number of predicted “Diabetes” cases across the confusion matrices does not reflect differing sample sizes, but rather differences in <strong>classification behavior</strong>.</p>
<p>The Random Forest is more conservative: it predicts far fewer positive cases, pushing more borderline individuals into the majority class (“No_Diabetes”). This reduces false positives but increases false negatives — a common trade-off when working with imbalanced data. Even so, the Random Forest still demonstrates superior overall performance when evaluated using our primary metrics.</p>
<p><strong>Performance Metrics</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Model</th>
<th>Log Loss ↓</th>
<th>Accuracy ↑</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Classification Tree</td>
<td><strong>0.3269909</strong></td>
<td><strong>0.8638591</strong></td>
</tr>
<tr class="even">
<td>Random Forest</td>
<td><strong>0.3195887</strong></td>
<td><strong>0.8645424</strong></td>
</tr>
</tbody>
</table>
<p><strong>Interpretation</strong></p>
<p><strong>Accuracy:</strong></p>
<ul>
<li><p>The Random Forest again performs slightly better (<strong>0.8645</strong> vs <strong>0.8639</strong>), correctly classifying more observations overall.</p></li>
<li><p>While the Random Forest predicts fewer individuals as “Diabetes,” it improves the overall fit of the probability model and provides more stable predictions.</p></li>
<li><p>Ensemble methods like random forests reduce variance by averaging many trees, which typically leads to better predictive performance than a single tree.</p></li>
</ul>
<p><strong>Log Loss:</strong></p>
<ul>
<li><p>Lower values indicate better-calibrated probability estimates</p></li>
<li><p>The Random Forest achieves a lower log loss (<strong>0.3196</strong> vs <strong>0.3270</strong>), meaning its predicted probabilities more closely match the true outcomes.</p></li>
</ul>
<p><strong>Conclusion</strong></p>
<p>Despite being more conservative in its classification decisions, the <strong>Random Forest</strong> produces <strong>better-calibrated probabilities</strong> and <strong>slightly higher accuracy</strong>, making it the overall best-performing model on the test set.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>